### ISSUE TITLE
Consider switching GitHub's default branch to sgx2

### ISSUE THREAD

**Issue by tjanez** [01org/linux-sgx-driver#100]
Even though the [README states it very clearly](https://github.com/intel/linux-sgx-driver#important):
> ### IMPORTANT:
> Starting from 5/10/2019, the master branch (which supports only SGX 1.5-based features) is deprecated and is not supported anymore. Please use the sgx2 branch; it is a super set of the master branch.

some people will still miss this and think there is no active development on this repository anymore.

Therefore, I suggest you [switch GitHub's default to branch](https://github.com/intel/linux-sgx-driver/settings/branches) to `sgx2` to avoid this.

**Comment by haitaohuang** [comment]
done
