### ISSUE TITLE
sgx driver should honer the address with MAP_FIXED

### ISSUE THREAD

**Issue by yamahata** [01org/linux-sgx-driver#113]
Currently mmap(addr=0, flags=MAP_FIXED) requires sysctl vm.mmap_addr_min=0 as system-wide configuration.
As MAP_FIXED is supplied, it should be honored.

**Comment by haitaohuang** [comment]
I'll close this one as we no longer add new features. The upstream and FLC drivers are already supporting this. So please use those drivers. Also I believe this change is not the only change needed for what you are doing.
