### ISSUE TITLE
Ubuntu installation problem

### ISSUE THREAD

**Issue by metegenez** [01org/linux-sgx-driver#126]
`sudo apt-get install linux-headers-$(uname -r)` part does not work for me. I am using WSL Ubuntu 18.04, it was a fresh installation. 

Error:
`E: Unable to locate package linux-headers-4.4.0-19041-Microsoft
E: Couldn't find any package by glob 'linux-headers-4.4.0-19041-Microsoft'
E: Couldn't find any package by regex 'linux-headers-4.4.0-19041-Microsoft'`

**Comment by haitaohuang** [comment]
No sure if you have a custom ubuntu image or kernel. try to search for the headers using apt-cache command. If you installed a custom kernel, then the headers should come from the source you get the kernel.
