### ISSUE TITLE
AESM Service can't access from China

### ISSUE THREAD

**Issue by jasl** [01org/linux-sgx-driver#128]
I don't know where I can push AESM Service's problem, but this emergency and embarrassing

<ps.sgx.trustedservices.intel.com> can't access from China, now, I believe it affact all SGX apps

![4401607081307_ pic](https://user-images.githubusercontent.com/1024162/101160948-cf764500-366a-11eb-81d0-546ddf9271ce.jpg)

**Comment by llly** [comment]
Thanks a lot. I can reproduce this issue. Sometimes accessing this URL shows the unexpected page. Sometimes it returns expected error code 405.

**Comment by jsun39** [comment]
We are working to address it. Thanks to report it.

**Comment by jasl** [comment]
> Thanks a lot. I can reproduce this issue. Sometimes accessing this URL shows the unexpected page. Sometimes it returns expected error code 405.

It depends on DNS resolve to where

typically, in Beijing

```
dig ps.sgx.trustedservices.intel.com

; <<>> DiG 9.10.6 <<>> ps.sgx.trustedservices.intel.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50330
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ps.sgx.trustedservices.intel.com. IN	A

;; ANSWER SECTION:
ps.sgx.trustedservices.intel.com. 862 IN CNAME	ps.sgx1.infra-host.com.
ps.sgx1.infra-host.com.	22	IN	CNAME	prc-ps.sgxprod.adsdcsp.com.
prc-ps.sgxprod.adsdcsp.com. 261	IN	A	40.126.120.63

;; Query time: 63 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Dec 07 14:04:26 CST 2020
;; MSG SIZE  rcvd: 136
```

If <ps.sgx.trustedservices.intel.com> redirect to <prc-ps.sgxprod.adsdcsp.com> you can 100% reproduce the problem.

**Comment by llly** [comment]
This issue should be fixed now.

**Comment by jasl** [comment]
thank you! I close the issue now

**Comment by ltinerary** [comment]
hello @jasl 
When I visit this site（[ps.sgx.trustedservices.intel.com](http://ps.sgx.trustedservices.intel.com/)）, it shows 403

<img width="826" alt="403forbidden" src="https://user-images.githubusercontent.com/79144923/116173419-23c7b180-a73f-11eb-88bf-eb56554751bb.png">

What is this website used for?
Thanks a lot ~

**Comment by jasl** [comment]
> hello @jasl
> When I visit this site（[ps.sgx.trustedservices.intel.com](http://ps.sgx.trustedservices.intel.com/)）, it shows 403
> 
> <img alt="403forbidden" width="826" src="https://user-images.githubusercontent.com/79144923/116173419-23c7b180-a73f-11eb-88bf-eb56554751bb.png">
> 
> What is this website used for?
> Thanks a lot ~

This is the IAS API site, not use for open in browser

**Comment by ltinerary** [comment]
> > hello @jasl
> > When I visit this site（[ps.sgx.trustedservices.intel.com](http://ps.sgx.trustedservices.intel.com/)）, it shows 403
> > <img alt="403forbidden" width="826" src="https://user-images.githubusercontent.com/79144923/116173419-23c7b180-a73f-11eb-88bf-eb56554751bb.png">
> > What is this website used for?
> > Thanks a lot ~
> 
> This is the IAS API site, not use for open in browser

Thank you！☺
