### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jethrogb** [01org/linux-sgx-driver#136]
There have been some changes over the past ~year, are you planning to do a new release?

**Comment by haitaohuang** [comment]
Actually, latest release on 01.org always have the latest of this driver: https://download.01.org/intel-sgx/sgx-linux/2.14/distro/ubuntu20.04-server/
We should have labeled and updated the versions here too.

**Comment by jethrogb** [comment]
Yes if you could apply the appropriate tags that would be helpful!
