### ISSUE TITLE
make fails: Skipping BTF generation for ...isgx.ko due to unavailability of vmlinux

### ISSUE THREAD

**Issue by sbellem** [01org/linux-sgx-driver#144]
Unable to build `isgx.ko`.

| | |
-- | --
operating system | Ubuntu 20.04
kernel | Linux 5.15.5-051505-generic
driver tag | [sgx_diver_2.14](https://github.com/intel/linux-sgx-driver/tree/sgx_diver_2.14) (2d2b795)

**note**: The same thing happens with `master` (54c9c4c1fe30f459abe7c4b9c153ed2967973c22).

```console
$ make
make -C /lib/modules/5.15.5-051505-generic/build M=/home/pi/intel/linux-sgx-driver modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.5-051505-generic'
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_main.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_page_cache.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_ioctl.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_vma.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_util.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_encl.o
  CC [M]  /home/pi/intel/linux-sgx-driver/sgx_encl2.o
  LD [M]  /home/pi/intel/linux-sgx-driver/isgx.o
  MODPOST /home/pi/intel/linux-sgx-driver/Module.symvers
  CC [M]  /home/pi/intel/linux-sgx-driver/isgx.mod.o
  LD [M]  /home/pi/intel/linux-sgx-driver/isgx.ko
  BTF [M] /home/pi/intel/linux-sgx-driver/isgx.ko
Skipping BTF generation for /home/pi/intel/linux-sgx-driver/isgx.ko due to unavailability of vmlinux
make[1]: Leaving directory '/usr/src/linux-headers-5.15.5-051505-generic'
```

**Comment by AnandakumarNatarajan** [comment]
+1 Facing the same issue.

**Comment by feknall** [comment]
Isn't there still any solutions for this problem?

**Comment by haitaohuang** [comment]
This is not a fatal error. The driver is still built. However, I notice you are using 5.11+ kernel which should already have sgx built-in. Unless you are using non-FLC, you should not need this driver. Our PSW would automatically use /dev/sgx/enclave if it exists and ignore /dev/isgx.

**Comment by ericyame** [comment]
Hi, I have the same issue with kernel 5.11. I don't see any sgx driver under /dev. Also I cannot build sgx driver like the original post. Any comment?

**Comment by oldoldcoder** [comment]
+1,can u solve?

**Comment by andyzyb** [comment]
kernel 5.11 should have built-in SGX driver, so you don't need to build this driver.
