### ISSUE TITLE
win的SGX SDK无法下载

### ISSUE THREAD

**Issue by Natruel** [01org/linux-sgx-driver#147]
intel的官网现在甚至不支持win的SGX SDK的下载，我去年十月份的时候还可以下载。你有什么比较好的解决办法吗。还有就是我现在电脑上有之前下载的SDK，但是点击安装的时候会自动闪退，我另一个电脑反而可以安装成功。不知道你有没有什么好的建议。

**Comment by llly** [comment]
https://lemcenter.intel.com/forms/?productId=ps_3074
 the link is from https://www.intel.com/content/www/us/en/developer/tools/software-guard-extensions/overview.html

You need an Intel account. Download link will be mailed after you request it.
