### ISSUE TITLE
Strange code in validate_secs.

### ISSUE THREAD

**Issue by fchai** [01org/linux-sgx-driver#15]
https://github.com/01org/linux-sgx-driver/blob/master/isgx_ioctl.c#L235

if ((secs->xfrm & BIT(3)) != (secs->xfrm & BIT(4)))
    return -EINVAL;

Only if BIT(3) and BIT(4) are both 0 at the same time, this expression is TRUE. If any one bit of BIT 3 and BIT 4 is 1, validate_secs will return -EINVAL.

I guess the real purpose is bit 3 and bit 4 must have the same value, both 0 or both 1?

Should like this:

if (((secs->xfrm >> 3) & 1) != ((secs->xfrm >> 4) & 1))
    return -EINVAL;

**Comment by ghost** [comment]
Has been fixed but not backported to the out-of-tree driver http://git.infradead.org/users/jjs/linux-isgx.git/blob/HEAD:/drivers/platform/x86/intel_sgx_ioctl.c. Unless this causes regression in a real-world environment I think we never fix this for the out-of-tree driver.
