### ISSUE TITLE
Hi question about sgx setting

### ISSUE THREAD

**Issue by leesera** [01org/linux-sgx-driver#25]
Hi, I have a problem to install isgx module.

My host machine spec is 
`cpu : i7-6700 , mainboard : X11SSZ-QF (supporting SGX)`
And I try to run sgx application through ubuntu 16.06 LTS with virtualbox. 

I put commands for installing sgx driver `isgx`
But the output of command `manprobe` is following

<img width="407" alt="2017-04-30 9 26 38" src="https://cloud.githubusercontent.com/assets/4794692/25564325/d426ac88-2deb-11e7-88d0-144af1461e26.png">

And the output of `dmesg` after that command is 
<img width="386" alt="2017-04-30 9 28 26" src="https://cloud.githubusercontent.com/assets/4794692/25564331/fb3ebd74-2deb-11e7-8cfb-6076379bf519.png">

I found the reason of that situation that [boot_cpu_has(X86_FEATURE_SGX)](https://github.com/jethrogb/sgx-utils/blob/master/isgx/isgx_main.c#L105l) returns false.

I do not know why that function does not return well:(
I already set `sgx bios setting` to be enabled

**Comment by sergeay** [comment]
The processor you have should have SGX but
it seems SGX has not been enabled.

To make sure of this, have you got the possibility to run cpuid with leaf 18 and sub-leaf 0.
The resulting eax should have the least significant bit equal to 1. If not SGX was not enabled by bios.

**Comment by leesera** [comment]
@sergeay thank you for replying my question:)
I already set my host machine to be SGX enabled by bios setting. (Window is running on my machine)
But it does not work in ubuntu which is running on virtualbox. Is there anything to set more?

**Comment by sergeay** [comment]
I got it.
You are using Ubuntu as a guest machine from a windows host machine.
SGX in a guest machine is not supported yet.
If you want Ubuntu to work with SGX, you will need to install it natively (bare metal).

**Comment by leesera** [comment]
@sergeay I understand what you mean. Thank you for helping me!
