### ISSUE TITLE
Is this repo the latest sgx driver code?

### ISSUE THREAD

**Issue by zzzzzzch** [01org/linux-sgx-driver#76]
Hi! 
+ I notice most of the repo's code are a year ago
+ But the latest sgx sdk when I write this issue is published on Dec 20, 2018.

So, I wonder whther the repo's code is latest? 
If not, where can I get the latest driver code?? 

Thanks!!!

**Comment by andyzyb** [comment]
Yes, it is the latest.  Driver code has less changes.

**Comment by zzzzzzch** [comment]
> Yes, it is the latest. Driver code has less changes.

Thanks!!
