### ISSUE TITLE
FTBFS with linux-4.20

### ISSUE THREAD

**Issue by mythi** [01org/linux-sgx-driver#77]
```
/opt/intel/sgxdriver/package/sgx_encl2.c: In function ‘sgx_encl_augment’:
/opt/intel/sgxdriver/package/sgx_encl2.c:172:8: error: implicit declaration of function ‘vm_insert_pfn’; did you mean ‘vmf_insert_pfn’? [-Werror=implicit-function-declaration]
  ret = vm_insert_pfn(vma, encl_page->addr, PFN_DOWN(epc_page->pa));
        ^~~~~~~~~~~~~
        vmf_insert_pfn
```

same with sgx_encl.c and sgx_util.c.

running sgx_linux_x64_driver_778dd1f.bin

**Comment by sergeay** [comment]
For which kernel are you compiling?

**Comment by mythi** [comment]
```
$ uname -r
4.20.3-685.native
```

**Comment by sergeay** [comment]
Yes, there is a change in kernel 4.20 that causes this build error and we are going to fix it.
Stay tuned or try an older kernel.

**Comment by mythi** [comment]
No worries, I'm not blocked because I can unpack the installer and

```
$ sed -i -e 's/vm_insert_pfn/vmf_insert_pfn/g' /opt/intel/sgxdriver/package/sgx_*.c
```

**Comment by mythi** [comment]
@sergeay there's also something else with 4.20: aesm_service fails to load AEs' with 4.20. The debug output is: 

```
[enclave_initialize sgx_enclave_common.cpp:467]
SGX_IOC_ENCLAVE_INIT failed error = 4
```

the same aesm_service binary starts OK with an older kernel (that unfortunately has a different .config too). Any ideas where to look?

**Comment by sergeay** [comment]
This is unexpected...
Can you do the following for me:
$ sudo su
$ echo module isgx +p > /sys/kernel/debug/dynamic_debug/control
$ dmesg -wT | grep sgx

then run your scenario and drop the above dmesg output here.
Thanks

**Comment by mythi** [comment]
```
[Mon Jan 28 13:59:43 2019] calling  init_sgx_module+0x0/0x60 [isgx] @ 266
[Mon Jan 28 13:59:43 2019] intel_sgx: Intel SGX Driver v0.11
[Mon Jan 28 13:59:43 2019] intel_sgx INT0E0C:00: EPC bank 0x70200000-0x76000000
[Mon Jan 28 13:59:43 2019] intel_sgx: second initialization call skipped
[Mon Jan 28 13:59:43 2019] probe of intel_sgx.0 returned 1 after 17 usecs
[Mon Jan 28 13:59:43 2019] initcall init_sgx_module+0x0/0x60 [isgx] returned 0 a                                  fter 22278 usecs
[Mon Jan 28 14:00:45 2019] intel_sgx: [786:0x00000000432c5878] EINIT returned 4
[Mon Jan 28 14:01:00 2019] intel_sgx: [814:0x000000002e384b53] EINIT returned 4
[Mon Jan 28 14:01:22 2019] intel_sgx: [838:0x000000000313851d] EINIT returned 4
[Mon Jan 28 14:02:06 2019] intel_sgx: [853:0x00000000966f5758] EINIT returned 4
```

The last line repeats for all ``` /opt/intel/sgxpsw/aesm/aesm_service``` attempts.

**Comment by sergeay** [comment]
Which version of psw are you using or do you build the open source package?

**Comment by mythi** [comment]
I'm pulling 'b2' branch from this repo, and psw (from linux-sgx) I've tried with master, 2.4, and 2.3.1.

**Comment by mythi** [comment]
I'm pulling 'b2' branch from this repo, and psw (from linux-sgx) I've tried with master, 2.4, and 2.3.1.

**Comment by sergeay** [comment]
I can see that. It is reproducible with 2.1 as well.
Possibly some system call in the kernel has changed its behavior or exposed a bug.
We will check it.

**Comment by sergeay** [comment]
I suppose you are not blocked in the mean time and can use 4.19 or an older kernel.

**Comment by mythi** [comment]
@sergeay thanks for your help! I'm not blocked now that I know where the problem is (would prefer to stay with my distro's default kernel though, which is 4.20)

**Comment by ghost** [comment]
Does the AESM failure only happen with kernel 4.2? Can you reproduce the same issue (EINIT returned 4) with 4.19?

**Comment by mythi** [comment]
@ZongminGu I'm not able to check with 4.19 today. I'll get back to that question later in the week. It worked with 4.18 for sure.

**Comment by mythi** [comment]
The latest master helps to get ```aesm.service``` running. The latest SDK/PSW causes ```SIGILL``` with the ```SampleEnclave``` but that's probably something else.
